import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import type { ProjectCommandCenterProjection } from "@liexiu/core/orchestration";
import { ProjectCommandCenter, type ProjectCommandCenterLabels } from "./project-command-center";

const labels: ProjectCommandCenterLabels = { project: "Project", missionPortfolio: "Missions", attentionQueue: "Attention", ownerActions: "Actions", capacity: "Capacity", agents: "Agents", runtimes: "Runtimes", capacityEmpty: "No capacity", missionCount: "Missions", activeMissions: "Active", blockedMissions: "Blocked", completedMissions: "Completed", attentionCount: "Attention", tokens: "Tokens", cost: "Cost", status: "Status", filter: "Filter", kindFilter: "Kind", severityFilter: "Severity", all: "All", sort: "Sort", updated: "Updated", risk: "Risk", progress: "Progress", noMissions: "No missions", noAttention: "No attention", evidence: "Evidence", revisions: "Revisions", requiredPermission: "Permission", riskLabel: "Risk", reason: "Reason", openMission: "Open", disabled: "Disabled", duties: "Duties", activeMissionsLabel: "Active missions", activeQueued: "Active/queued", refresh: "Refresh", refreshing: "Refreshing", truncated: "Truncated", actionLabels: { inspect: "Inspect", approve_budget: "Approve budget", approve_plan: "Approve plan", reject_plan: "Reject plan", retry_task: "Retry", resolve_human_gate: "Resolve gate", reassign_task: "Reassign", cancel_mission: "Cancel" }, statusLabels: { all: "All", draft: "Draft", ready: "Ready", running: "Running", blocked: "Blocked", completed: "Completed", failed: "Failed", cancelled: "Cancelled" }, severityLabels: { all: "All", critical: "Critical", high: "High", attention: "Attention" }, kindLabels: { mission_blocked: "Blocked", budget_approval: "Budget", budget_exceeded: "Budget exceeded", review_pending: "Review", run_failed: "Failed", dispatch_timeout: "Dispatch timeout", run_timeout: "Run timeout", plan_proposal_pending: "Plan", human_gate: "Gate", runtime_offline: "Offline" } };
const base = (overrides: Partial<ProjectCommandCenterProjection["missions"][number]> = {}): ProjectCommandCenterProjection["missions"][number] => ({ id: "m1", title: "Mission one", status: "running", currentPhase: "run", progress: { completed: 1, total: 2, percent: 50 }, budget: { status: "ok", consumedTokens: 1, reservedTokens: 2, consumedCostUsdTicks: 3, reservedCostUsdTicks: 4, grantTokens: 0, grantCostUsdTicks: 0 }, revision: 7, lastSequence: 1, updatedAt: "2026-08-19T00:00:00+00:00", pendingHumanGates: 0, pendingReviews: 0, pendingPlanProposals: 0, offlineAgents: 0, activeRuns: 1, queuedRuns: 0, ...overrides });
const projection: ProjectCommandCenterProjection = { project: { id: "p1", title: "Project", status: "in_progress", updatedAt: "2026-08-19T00:00:00+00:00" }, generatedAt: "2026-08-19T00:00:00+00:00", truncated: false, missions: [base(), base({ id: "m2", title: "Blocked mission", status: "blocked", updatedAt: "2026-08-18T00:00:00+00:00", progress: { completed: 2, total: 2, percent: 100 } })], attention: [{ id: "a1", missionId: "m2", kind: "mission_blocked", severity: "critical", subjectType: "task_node", subjectId: "node-2", taskNodeId: "node-2", runId: "run-2", artifactId: "artifact-2", gateId: "gate-2", missionRevision: 9, taskRevision: 4, gateRevision: 5, actions: [{ kind: "reassign_task", enabled: true, risk: "high", reasonCode: "not_supported", requiredPermission: "mission:command" }, { kind: "inspect", enabled: true, risk: "low", reasonCode: "ready", requiredPermission: "project:read" }] }], capacity: { agents: [{ id: "agent", name: "Agent", status: "online", duties: ["executor"], activeMissionIds: ["m1"], activeRuns: 1, queuedRuns: 2 }], runtimes: [] }, totals: { missionCount: 2, activeMissions: 1, blockedMissions: 1, completedMissions: 0, attentionCount: 1, activeRuns: 1, queuedRuns: 2, offlineAgents: 0, pendingHumanGates: 0, pendingReviews: 0, consumedTokens: 1, reservedTokens: 2, consumedCostUsdTicks: 3, reservedCostUsdTicks: 4 } };

describe("ProjectCommandCenter", () => {
  it("filters, sorts, drills down, and renders capacity", () => { const open = vi.fn(); render(<ProjectCommandCenter projection={projection} labels={labels} onOpenMission={open} />); fireEvent.change(screen.getByLabelText("Sort"), { target: { value: "progress" } }); const missionButtons = screen.getAllByRole("button").filter((button) => button.textContent?.includes("mission")); expect(missionButtons[0]).toHaveTextContent("Blocked mission"); fireEvent.change(screen.getByLabelText("Status"), { target: { value: "blocked" } }); fireEvent.click(screen.getByText("Blocked mission")); expect(open).toHaveBeenCalledWith({ missionId: "m2" }); expect(screen.getByText("Agent")).toBeInTheDocument(); expect(screen.getByText("No capacity")).toBeInTheDocument(); });
  it("filters attention, carries complete evidence deep-link, and disables reassign", () => { const open = vi.fn(); render(<ProjectCommandCenter projection={projection} labels={labels} onOpenMission={open} />); fireEvent.change(screen.getByLabelText("Severity"), { target: { value: "high" } }); expect(screen.getByText("No attention")).toBeInTheDocument(); fireEvent.change(screen.getByLabelText("Severity"), { target: { value: "critical" } }); expect(screen.getByText(/node-2/)).toBeInTheDocument(); const reassign = screen.getByRole("button", { name: /Reassign/ }); expect(reassign).toBeDisabled(); fireEvent.click(reassign); expect(open).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Inspect" })); expect(open).toHaveBeenCalledWith({ missionId: "m2", taskNodeId: "node-2", runId: "run-2", artifactId: "artifact-2", gateId: "gate-2", actionKind: "inspect" }); expect(screen.getByText(/Permission: project:read/)).toBeInTheDocument(); });
});
